# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/b2000.xdc

# Block Designs: bd/zynq_iic/zynq_iic.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic || ORIG_REF_NAME==zynq_iic}]

# IP: bd/zynq_iic/ip/zynq_iic_processing_system7_0_0/zynq_iic_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic_processing_system7_0_0 || ORIG_REF_NAME==zynq_iic_processing_system7_0_0}]

# IP: bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_iic_proc_sys_reset_0_0}]

# IP: bd/zynq_iic/ip/zynq_iic_axi_gpio_0_0/zynq_iic_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic_axi_gpio_0_0 || ORIG_REF_NAME==zynq_iic_axi_gpio_0_0}]

# IP: bd/zynq_iic/ip/zynq_iic_ps7_0_axi_periph_1_0/zynq_iic_ps7_0_axi_periph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic_ps7_0_axi_periph_1_0 || ORIG_REF_NAME==zynq_iic_ps7_0_axi_periph_1_0}]

# IP: bd/zynq_iic/ip/zynq_iic_axi_uartlite_0_0/zynq_iic_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic_axi_uartlite_0_0 || ORIG_REF_NAME==zynq_iic_axi_uartlite_0_0}]

# IP: bd/zynq_iic/ip/zynq_iic_xbar_0/zynq_iic_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic_xbar_0 || ORIG_REF_NAME==zynq_iic_xbar_0}]

# IP: bd/zynq_iic/ip/zynq_iic_auto_pc_0/zynq_iic_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_iic_auto_pc_0 || ORIG_REF_NAME==zynq_iic_auto_pc_0}]

# XDC: bd/zynq_iic/zynq_iic_ooc.xdc
