# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nandykong/zynq_iic/zynq_iic.cache/wt [current_project]
set_property parent.project_path /home/nandykong/zynq_iic/zynq_iic.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/nandykong/zynq_iic/zynq_iic.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/hdl/zynq_iic_wrapper.v
add_files /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/zynq_iic.bd
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_processing_system7_0_0/zynq_iic_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_axi_gpio_0_0/zynq_iic_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_axi_gpio_0_0/zynq_iic_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_axi_gpio_0_0/zynq_iic_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_axi_uartlite_0_0/zynq_iic_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_axi_uartlite_0_0/zynq_iic_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_axi_uartlite_0_0/zynq_iic_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_xbar_0/zynq_iic_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_auto_pc_0/zynq_iic_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/zynq_iic_ooc.xdc]
set_property is_locked true [get_files /home/nandykong/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/zynq_iic.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nandykong/zynq_iic/zynq_iic.srcs/constrs_3/new/b2000.xdc
set_property used_in_implementation false [get_files /home/nandykong/zynq_iic/zynq_iic.srcs/constrs_3/new/b2000.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zynq_iic_wrapper -part xc7z045ffg900-1


write_checkpoint -force -noxdef zynq_iic_wrapper.dcp

catch { report_utilization -file zynq_iic_wrapper_utilization_synth.rpt -pb zynq_iic_wrapper_utilization_synth.pb }
