set_property SRC_FILE_INFO {cfile:/home/wesleyguo/github/vivado/vivado/2000t_c2c_bram/b2000t_c2c_bram/b2000t_c2c_bram.srcs/constrs_1/new/b2000t_c2c_bram.xdc rfile:../../../b2000t_c2c_bram.srcs/constrs_1/new/b2000t_c2c_bram.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K41 [get_ports CLK_IN1_D_clk_p]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M42 [get_ports INIT_DIFF_CLK_clk_p]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA8 [get_ports GT_DIFF_REFCLK1_clk_p]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV6 [get_ports {GT_SERIAL_RX_rxp[0]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA22 [get_ports {pma_init_out[0]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports axi_c2c_link_status_out]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports axi_c2c_config_error_out]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports axi_c2c_multi_bit_error_out]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B24  [get_ports ext_reset_in]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA23 [get_ports ext_reset_out]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA22 [get_ports {pma_init_out[0]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L18	[	get_ports	pin_a[0]	]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K18	[	get_ports	pin_a[1]	]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C17	[	get_ports	pin_a[2]	]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C16	[	get_ports	pin_a[3]	]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B17	[	get_ports	pin_a[4]	]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A17	[	get_ports	pin_a[5]	]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F17	[	get_ports	pin_a[6]	]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E17	[	get_ports	pin_a[7]	]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G10	[	get_ports	pin_a[8]	]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F10	[	get_ports	pin_a[9]	]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A10	[	get_ports	pin_a[10]	]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A9	[	get_ports	pin_a[11]	]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F15	[	get_ports	pin_a[12]	]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E15	[	get_ports	pin_a[13]	]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H11	[	get_ports	pin_a[14]	]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G11	[	get_ports	pin_a[15]	]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M15	[	get_ports	pin_a[16]	]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L14	[	get_ports	pin_a[17]	]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M20	[	get_ports	pin_a[18]	]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L20	[	get_ports	pin_a[19]	]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J13	[	get_ports	pin_a[20]	]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H13	[	get_ports	pin_a[21]	]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J18	[	get_ports	pin_a[22]	]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H18	[	get_ports	pin_a[23]	]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K10	[	get_ports	pin_a[24]	]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J10	[	get_ports	pin_a[25]	]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D20	[	get_ports	pin_a[26]	]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D19	[	get_ports	pin_a[27]	]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C21	[	get_ports	pin_a[28]	]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B21	[	get_ports	pin_a[29]	]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J19	[	get_ports	pin_a[30]	]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H19	[	get_ports	pin_a[31]	]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H16	[	get_ports	pin_a[32]	]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G16	[	get_ports	pin_a[33]	]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E11	[	get_ports	pin_a[34]	]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D11	[	get_ports	pin_a[35]	]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B16	[	get_ports	pin_a[36]	]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B15	[	get_ports	pin_a[37]	]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B11	[	get_ports	pin_a[38]	]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B10	[	get_ports	pin_a[39]	]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A15	[	get_ports	pin_a[40]	]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A14	[	get_ports	pin_a[41]	]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K11	[	get_ports	pin_a[42]	]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J11	[	get_ports	pin_a[43]	]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B9	[	get_ports	pin_a[44]	]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A8	[	get_ports	pin_a[45]	]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J14	[	get_ports	pin_a[46]	]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H14	[	get_ports	pin_a[47]	]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B14	[	get_ports	pin_a[48]	]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A13	[	get_ports	pin_a[49]	]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N16	[	get_ports	pin_a[50]	]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M16	[	get_ports	pin_a[51]	]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E13	[	get_ports	pin_a[52]	]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D13	[	get_ports	pin_a[53]	]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	T15	[	get_ports	pin_a[54]	]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R15	[	get_ports	pin_a[55]	]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L17	[	get_ports	pin_a[56]	]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K17	[	get_ports	pin_a[57]	]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D9	[	get_ports	pin_a[58]	]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C9	[	get_ports	pin_a[59]	]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G15	[	get_ports	pin_b[0]	]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G14	[	get_ports	pin_b[1]	]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C12	[	get_ports	pin_b[2]	]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C11	[	get_ports	pin_b[3]	]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F12	[	get_ports	pin_b[4]	]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E12	[	get_ports	pin_b[5]	]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D18	[	get_ports	pin_b[6]	]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C18	[	get_ports	pin_b[7]	]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N14	[	get_ports	pin_b[8]	]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M14	[	get_ports	pin_b[9]	]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B20	[	get_ports	pin_b[10]	]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A20	[	get_ports	pin_b[11]	]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E16	[	get_ports	pin_b[12]	]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D16	[	get_ports	pin_b[13]	]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A19	[	get_ports	pin_b[14]	]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A18	[	get_ports	pin_b[15]	]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H17	[	get_ports	pin_b[16]	]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G17	[	get_ports	pin_b[17]	]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B12	[	get_ports	pin_b[18]	]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A12	[	get_ports	pin_b[19]	]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C14	[	get_ports	pin_b[20]	]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C13	[	get_ports	pin_b[21]	]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K15	[	get_ports	pin_b[22]	]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J15	[	get_ports	pin_b[23]	]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F14	[	get_ports	pin_b[24]	]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F13	[	get_ports	pin_b[25]	]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C19	[	get_ports	pin_b[26]	]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B19	[	get_ports	pin_b[27]	]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D15	[	get_ports	pin_b[28]	]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D14	[	get_ports	pin_b[29]	]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L12	[	get_ports	pin_b[30]	]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K12	[	get_ports	pin_b[31]	]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P15	[	get_ports	pin_b[32]	]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P14	[	get_ports	pin_b[33]	]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G9	[	get_ports	pin_b[34]	]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F9	[	get_ports	pin_b[35]	]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E10	[	get_ports	pin_b[36]	]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D10	[	get_ports	pin_b[37]	]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J9	[	get_ports	pin_b[38]	]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H9	[	get_ports	pin_b[39]	]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N11	[	get_ports	pin_b[40]	]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M11	[	get_ports	pin_b[41]	]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H12	[	get_ports	pin_b[42]	]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G12	[	get_ports	pin_b[43]	]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K16	[	get_ports	pin_b[44]	]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J16	[	get_ports	pin_b[45]	]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R16	[	get_ports	pin_b[46]	]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P16	[	get_ports	pin_b[47]	]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P13	[	get_ports	pin_b[48]	]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N13	[	get_ports	pin_b[49]	]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N12	[	get_ports	pin_b[50]	]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M12	[	get_ports	pin_b[51]	]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	T13	[	get_ports	pin_b[52]	]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R13	[	get_ports	pin_b[53]	]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M19	[	get_ports	pin_b[54]	]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L19	[	get_ports	pin_b[55]	]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R11	[	get_ports	pin_b[56]	]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P11	[	get_ports	pin_b[57]	]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	T12	[	get_ports	pin_b[58]	]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R12	[	get_ports	pin_b[59]	]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E23	[	get_ports	pin_a_1[0]	]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F23	[	get_ports	pin_a_1[1]	]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P21	[	get_ports	pin_a_1[2]	]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R21	[	get_ports	pin_a_1[3]	]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E22	[	get_ports	pin_a_1[4]	]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F22	[	get_ports	pin_a_1[5]	]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G26	[	get_ports	pin_a_1[6]	]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H26	[	get_ports	pin_a_1[7]	]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J28	[	get_ports	pin_a_1[8]	]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K28	[	get_ports	pin_a_1[9]	]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R23	[	get_ports	pin_a_1[10]	]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	T23	[	get_ports	pin_a_1[11]	]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H24	[	get_ports	pin_a_1[12]	]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J24	[	get_ports	pin_a_1[13]	]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N24	[	get_ports	pin_a_1[14]	]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P24	[	get_ports	pin_a_1[15]	]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F24	[	get_ports	pin_a_1[16]	]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G24	[	get_ports	pin_a_1[17]	]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H23	[	get_ports	pin_a_1[18]	]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J23	[	get_ports	pin_a_1[19]	]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A25	[	get_ports	pin_a_1[20]	]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B25	[	get_ports	pin_a_1[21]	]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K25	[	get_ports	pin_a_1[22]	]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L25	[	get_ports	pin_a_1[23]	]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F25	[	get_ports	pin_a_1[24]	]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G25	[	get_ports	pin_a_1[25]	]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J31	[	get_ports	pin_a_1[26]	]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K31	[	get_ports	pin_a_1[27]	]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J26	[	get_ports	pin_a_1[28]	]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K26	[	get_ports	pin_a_1[29]	]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M31	[	get_ports	pin_a_1[30]	]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M30	[	get_ports	pin_a_1[31]	]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E28	[	get_ports	pin_a_1[32]	]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F28	[	get_ports	pin_a_1[33]	]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F27	[	get_ports	pin_a_1[34]	]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G27	[	get_ports	pin_a_1[35]	]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C33	[	get_ports	pin_a_1[36]	]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D33	[	get_ports	pin_a_1[37]	]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E27	[	get_ports	pin_a_1[38]	]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E26	[	get_ports	pin_a_1[39]	]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P26	[	get_ports	pin_a_1[40]	]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R26	[	get_ports	pin_a_1[41]	]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C28	[	get_ports	pin_a_1[42]	]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C27	[	get_ports	pin_a_1[43]	]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L30	[	get_ports	pin_a_1[44]	]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L29	[	get_ports	pin_a_1[45]	]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E33	[	get_ports	pin_a_1[46]	]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F33	[	get_ports	pin_a_1[47]	]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B31	[	get_ports	pin_a_1[48]	]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B30	[	get_ports	pin_a_1[49]	]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E32	[	get_ports	pin_a_1[50]	]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F32	[	get_ports	pin_a_1[51]	]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G32	[	get_ports	pin_a_1[52]	]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G31	[	get_ports	pin_a_1[53]	]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G30	[	get_ports	pin_a_1[54]	]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H29	[	get_ports	pin_a_1[55]	]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J30	[	get_ports	pin_a_1[56]	]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K30	[	get_ports	pin_a_1[57]	]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H32	[	get_ports	pin_a_1[58]	]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H31	[	get_ports	pin_a_1[59]	]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N21	[	get_ports	pin_b_1[0]	]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N22	[	get_ports	pin_b_1[1]	]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M26	[	get_ports	pin_b_1[2]	]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M25	[	get_ports	pin_b_1[3]	]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R22	[	get_ports	pin_b_1[4]	]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	T22	[	get_ports	pin_b_1[5]	]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N27	[	get_ports	pin_b_1[6]	]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N26	[	get_ports	pin_b_1[7]	]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N23	[	get_ports	pin_b_1[8]	]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P23	[	get_ports	pin_b_1[9]	]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L28	[	get_ports	pin_b_1[10]	]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M27	[	get_ports	pin_b_1[11]	]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A28	[	get_ports	pin_b_1[12]	]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A27	[	get_ports	pin_b_1[13]	]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N28	[	get_ports	pin_b_1[14]	]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P28	[	get_ports	pin_b_1[15]	]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	P25	[	get_ports	pin_b_1[16]	]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R25	[	get_ports	pin_b_1[17]	]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K27	[	get_ports	pin_b_1[18]	]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L27	[	get_ports	pin_b_1[19]	]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R27	[	get_ports	pin_b_1[20]	]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	T27	[	get_ports	pin_b_1[21]	]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C26	[	get_ports	pin_b_1[22]	]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D26	[	get_ports	pin_b_1[23]	]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	R28	[	get_ports	pin_b_1[24]	]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	T28	[	get_ports	pin_b_1[25]	]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A30	[	get_ports	pin_b_1[26]	]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A29	[	get_ports	pin_b_1[27]	]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M29	[	get_ports	pin_b_1[28]	]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N29	[	get_ports	pin_b_1[29]	]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D31	[	get_ports	pin_b_1[30]	]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E31	[	get_ports	pin_b_1[31]	]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	M32	[	get_ports	pin_b_1[32]	]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N31	[	get_ports	pin_b_1[33]	]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N33	[	get_ports	pin_b_1[34]	]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	N32	[	get_ports	pin_b_1[35]	]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H28	[	get_ports	pin_b_1[36]	]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H27	[	get_ports	pin_b_1[37]	]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B27	[	get_ports	pin_b_1[38]	]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B26	[	get_ports	pin_b_1[39]	]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D29	[	get_ports	pin_b_1[40]	]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D28	[	get_ports	pin_b_1[41]	]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F29	[	get_ports	pin_b_1[42]	]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	G29	[	get_ports	pin_b_1[43]	]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B29	[	get_ports	pin_b_1[44]	]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C29	[	get_ports	pin_b_1[45]	]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	B32	[	get_ports	pin_b_1[46]	]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C32	[	get_ports	pin_b_1[47]	]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	E30	[	get_ports	pin_b_1[48]	]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	F30	[	get_ports	pin_b_1[49]	]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A33	[	get_ports	pin_b_1[50]	]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	A32	[	get_ports	pin_b_1[51]	]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K33	[	get_ports	pin_b_1[52]	]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	K32	[	get_ports	pin_b_1[53]	]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	H33	[	get_ports	pin_b_1[54]	]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	J33	[	get_ports	pin_b_1[55]	]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	C31	[	get_ports	pin_b_1[56]	]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	D30	[	get_ports	pin_b_1[57]	]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L33	[	get_ports	pin_b_1[58]	]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property	PACKAGE_PIN	L32	[	get_ports	pin_b_1[59]	]
