# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/jtag_axi_system_ila_0_0.xci
# IP: The module: 'jtag_axi_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/bd_3457.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457 || ORIG_REF_NAME==bd_3457}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_0/bd_3457_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_ila_lib_0 || ORIG_REF_NAME==bd_3457_ila_lib_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_1/bd_3457_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_g_inst_0 || ORIG_REF_NAME==bd_3457_g_inst_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_2/bd_3457_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_aw_0 || ORIG_REF_NAME==bd_3457_slot_0_aw_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_3/bd_3457_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_w_0 || ORIG_REF_NAME==bd_3457_slot_0_w_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_4/bd_3457_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_b_0 || ORIG_REF_NAME==bd_3457_slot_0_b_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_5/bd_3457_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_ar_0 || ORIG_REF_NAME==bd_3457_slot_0_ar_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_6/bd_3457_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_r_0 || ORIG_REF_NAME==bd_3457_slot_0_r_0}]

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3457_ila_lib_0 || ORIG_REF_NAME==bd_3457_ila_lib_0}] {/inst }]/inst ]]

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_0/bd_3457_ila_lib_0_ooc.xdc

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_1/bd_3457_g_inst_0_ooc.xdc

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/bd_3457_ooc.xdc

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/jtag_axi_system_ila_0_0.xci
# IP: The module: 'jtag_axi_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/bd_3457.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457 || ORIG_REF_NAME==bd_3457}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_0/bd_3457_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_ila_lib_0 || ORIG_REF_NAME==bd_3457_ila_lib_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_1/bd_3457_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_g_inst_0 || ORIG_REF_NAME==bd_3457_g_inst_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_2/bd_3457_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_aw_0 || ORIG_REF_NAME==bd_3457_slot_0_aw_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_3/bd_3457_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_w_0 || ORIG_REF_NAME==bd_3457_slot_0_w_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_4/bd_3457_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_b_0 || ORIG_REF_NAME==bd_3457_slot_0_b_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_5/bd_3457_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_ar_0 || ORIG_REF_NAME==bd_3457_slot_0_ar_0}]

# IP: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_6/bd_3457_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3457_slot_0_r_0 || ORIG_REF_NAME==bd_3457_slot_0_r_0}]

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3457_ila_lib_0 || ORIG_REF_NAME==bd_3457_ila_lib_0}] {/inst }]/inst ]]

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_0/bd_3457_ila_lib_0_ooc.xdc

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/ip/ip_1/bd_3457_g_inst_0_ooc.xdc

# XDC: /home/wesleyguo/github/vivado/vivado/jtag_c2c/jtag_c2c/jtag_c2c.srcs/sources_1/bd/jtag_axi/ip/jtag_axi_system_ila_0_0/bd_0/bd_3457_ooc.xdc
