#!/bin/bash -f
# Vivado (TM) v2016.4 (64-bit)
#
# Filename    : b2000t_c2c_bram.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jun 21 17:47:01 EDT 2017
# IP Build 1731160 on Wed Dec 14 23:47:21 MST 2016 
#
# usage: b2000t_c2c_bram.sh [-help]
# usage: b2000t_c2c_bram.sh [-lib_map_path]
# usage: b2000t_c2c_bram.sh [-noclean_files]
# usage: b2000t_c2c_bram.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'b2000t_c2c_bram.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm fifo_generator_v13_1_3 axi_chip2chip_v4_2_11 blk_mem_gen_v8_3_5 axi_bram_ctrl_v4_0_10 lib_cdc_v1_0_2 proc_sys_reset_v5_0_10 jtag_axi generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_11 axi_data_fifo_v2_1_10 axi_crossbar_v2_1_12)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "b2000t_c2c_bram.sh - Script generated by export_simulation (Vivado v2016.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "/home/vivado/vivado201604/Vivado/2016.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/vivado/vivado201604/Vivado/2016.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/vivado/vivado201604/Vivado/2016.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/564d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_3 $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/564d/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/564d/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_chip2chip_v4_2_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0c6f/hdl/axi_chip2chip_v4_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_chip2chip_0_0/sim/b2000t_c2c_bram_axi_chip2chip_0_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_aurora_lane.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_rx_startup_fsm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_tx_startup_fsm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_support.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_gt_common_wrapper.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_support_reset_logic.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_clock_module.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_standard_cc_module.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_reset_logic.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_cdc_sync.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0_core.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/example_design/b2000t_c2c_bram_aurora_64b66b_0_0_axi_to_drp.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_axi_to_ll.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_block_sync_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_common_reset_cbcc.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_common_logic_cbcc.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_cbcc_gtx_6466.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_channel_err_detect.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_channel_init_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_ch_bond_code_gen.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_64b66b_descrambler.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_err_detect.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_global_logic.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/example_design/gt/b2000t_c2c_bram_aurora_64b66b_0_0_wrapper.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_lane_init_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_ll_to_axi.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/example_design/gt/b2000t_c2c_bram_aurora_64b66b_0_0_multi_wrapper.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_rx_stream_datapath.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_rx_stream.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_width_conversion.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_64b66b_scrambler.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_sym_dec.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_sym_gen.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/example_design/gt/b2000t_c2c_bram_aurora_64b66b_0_0_gtx.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_tx_stream_control_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_tx_stream_datapath.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0/src/b2000t_c2c_bram_aurora_64b66b_0_0_tx_stream.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6273/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_blk_mem_gen_0_0/sim/b2000t_c2c_bram_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_10 $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/91f5/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_0_0/sim/b2000t_c2c_bram_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_clk_wiz_0/b2000t_c2c_bram_clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_clk_wiz_0/b2000t_c2c_bram_clk_wiz_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_rst_clk_wiz_100M_0/sim/b2000t_c2c_bram_rst_clk_wiz_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_vio_0_0/sim/b2000t_c2c_bram_vio_0_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/hdl/bd_6d24.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_0/sim/bd_6d24_ila_lib_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_1/bd_6d24_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_1/sim/bd_6d24_g_inst_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/2e37/xlconcat.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_2/sim/bd_6d24_slot_0_aw_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_3/sim/bd_6d24_slot_0_w_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_4/sim/bd_6d24_slot_0_b_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_5/sim/bd_6d24_slot_0_ar_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/bd_0/ip/ip_6/sim/bd_6d24_slot_0_r_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/sim/b2000t_c2c_bram_system_ila_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work jtag_axi $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6ffe/hdl/jtag_axi_v1_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_jtag_axi_0_0/sim/b2000t_c2c_bram_jtag_axi_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0b6b/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/39ba/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/896d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_xbar_0/sim/b2000t_c2c_bram_xbar_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila1_0/bd_0/hdl/bd_2221.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila1_0/bd_0/ip/ip_0/sim/bd_2221_ila_lib_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila1_0/bd_0/ip/ip_1/bd_2221_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila1_0/bd_0/ip/ip_1/sim/bd_2221_g_inst_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila1_0/sim/b2000t_c2c_bram_system_ila1_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/e147/xlconstant.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_xlconstant_0_0/sim/b2000t_c2c_bram_xlconstant_0_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_aurora_lane.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_rx_startup_fsm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_tx_startup_fsm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_standard_cc_module.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_reset_logic.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_cdc_sync.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1_core.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/example_design/b2000t_c2c_bram_aurora_64b66b_0_1_axi_to_drp.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_axi_to_ll.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_block_sync_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_common_reset_cbcc.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_common_logic_cbcc.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_cbcc_gtx_6466.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_channel_err_detect.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_channel_init_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_ch_bond_code_gen.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_64b66b_descrambler.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_err_detect.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_global_logic.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/example_design/gt/b2000t_c2c_bram_aurora_64b66b_0_1_wrapper.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_lane_init_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_ll_to_axi.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/example_design/gt/b2000t_c2c_bram_aurora_64b66b_0_1_multi_wrapper.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_rx_stream_datapath.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_rx_stream.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_width_conversion.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_64b66b_scrambler.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_sym_dec.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_sym_gen.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/example_design/gt/b2000t_c2c_bram_aurora_64b66b_0_1_gtx.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_tx_stream_control_sm.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_tx_stream_datapath.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1/src/b2000t_c2c_bram_aurora_64b66b_0_1_tx_stream.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_chip2chip_0_1/sim/b2000t_c2c_bram_axi_chip2chip_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_1_0/sim/b2000t_c2c_bram_axi_bram_ctrl_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_1_bram_1/sim/b2000t_c2c_bram_axi_bram_ctrl_1_bram_1.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6848/dut.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_dut_0_0/sim/b2000t_c2c_bram_dut_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_0_1/sim/b2000t_c2c_bram_axi_bram_ctrl_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/100a" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/6e61/hdl" +incdir+"$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ipshared/4f58/jack.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_jack_0_0/sim/b2000t_c2c_bram_jack_0_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila2_0/bd_0/hdl/bd_22d1.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila2_0/bd_0/ip/ip_0/sim/bd_22d1_ila_lib_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila2_0/sim/b2000t_c2c_bram_system_ila2_0.v" \
    "$ref_dir/../../../../b2000t_c2c_bram.srcs/sources_1/bd/b2000t_c2c_bram/hdl/b2000t_c2c_bram.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.b2000t_c2c_bram xil_defaultlib.glbl -o b2000t_c2c_bram_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./b2000t_c2c_bram_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./b2000t_c2c_bram.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/wesleyguo/github/vivado/vivado/2000t_c2c_bram/b2000t_c2c_bram/b2000t_c2c_bram.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key b2000t_c2c_bram_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc b2000t_c2c_bram_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./b2000t_c2c_bram.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: b2000t_c2c_bram.sh [-help]\n\
Usage: b2000t_c2c_bram.sh [-lib_map_path]\n\
Usage: b2000t_c2c_bram.sh [-reset_run]\n\
Usage: b2000t_c2c_bram.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
