# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/jtag_axi.xdc

# Block Designs: bd/jtag_axi/jtag_axi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi || ORIG_REF_NAME==jtag_axi}]

# IP: bd/jtag_axi/ip/jtag_axi_jtag_axi_0_0/jtag_axi_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_jtag_axi_0_0 || ORIG_REF_NAME==jtag_axi_jtag_axi_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_axi_bram_ctrl_0_0/jtag_axi_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_axi_bram_ctrl_0_0 || ORIG_REF_NAME==jtag_axi_axi_bram_ctrl_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_blk_mem_gen_0_0/jtag_axi_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_blk_mem_gen_0_0 || ORIG_REF_NAME==jtag_axi_blk_mem_gen_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_axi_mem_intercon_0/jtag_axi_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_axi_mem_intercon_0 || ORIG_REF_NAME==jtag_axi_axi_mem_intercon_0}]

# IP: bd/jtag_axi/ip/jtag_axi_clk_wiz_0/jtag_axi_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_clk_wiz_0 || ORIG_REF_NAME==jtag_axi_clk_wiz_0}]

# IP: bd/jtag_axi/ip/jtag_axi_rst_clk_wiz_100M_0/jtag_axi_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_rst_clk_wiz_100M_0 || ORIG_REF_NAME==jtag_axi_rst_clk_wiz_100M_0}]

# IP: bd/jtag_axi/ip/jtag_axi_vio_0_0/jtag_axi_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_vio_0_0 || ORIG_REF_NAME==jtag_axi_vio_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_axi_perf_mon_0_0/jtag_axi_axi_perf_mon_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_axi_perf_mon_0_0 || ORIG_REF_NAME==jtag_axi_axi_perf_mon_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_axi_hwicap_0_0/jtag_axi_axi_hwicap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_axi_hwicap_0_0 || ORIG_REF_NAME==jtag_axi_axi_hwicap_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_xbar_0/jtag_axi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_xbar_0 || ORIG_REF_NAME==jtag_axi_xbar_0}]

# IP: bd/jtag_axi/ip/jtag_axi_system_ila_0_0/jtag_axi_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_system_ila_0_0 || ORIG_REF_NAME==jtag_axi_system_ila_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_axi_chip2chip_0_0/jtag_axi_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_axi_chip2chip_0_0 || ORIG_REF_NAME==jtag_axi_axi_chip2chip_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_aurora_64b66b_0_0/jtag_axi_aurora_64b66b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_aurora_64b66b_0_0 || ORIG_REF_NAME==jtag_axi_aurora_64b66b_0_0}]

# IP: bd/jtag_axi/ip/jtag_axi_auto_pc_0/jtag_axi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_auto_pc_0 || ORIG_REF_NAME==jtag_axi_auto_pc_0}]

# IP: bd/jtag_axi/ip/jtag_axi_auto_pc_1/jtag_axi_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_auto_pc_1 || ORIG_REF_NAME==jtag_axi_auto_pc_1}]

# XDC: bd/jtag_axi/jtag_axi_ooc.xdc
