# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/b2000t_c2c_bram.xdc

# Block Designs: bd/b2000t_c2c_bram/b2000t_c2c_bram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram || ORIG_REF_NAME==b2000t_c2c_bram}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_chip2chip_0_0/b2000t_c2c_bram_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_axi_chip2chip_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_axi_chip2chip_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_0/b2000t_c2c_bram_aurora_64b66b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_aurora_64b66b_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_aurora_64b66b_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_blk_mem_gen_0_0/b2000t_c2c_bram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_blk_mem_gen_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_blk_mem_gen_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_0_0/b2000t_c2c_bram_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_mem_intercon_0/b2000t_c2c_bram_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_axi_mem_intercon_0 || ORIG_REF_NAME==b2000t_c2c_bram_axi_mem_intercon_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_clk_wiz_0/b2000t_c2c_bram_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_clk_wiz_0 || ORIG_REF_NAME==b2000t_c2c_bram_clk_wiz_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_rst_clk_wiz_100M_0/b2000t_c2c_bram_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_rst_clk_wiz_100M_0 || ORIG_REF_NAME==b2000t_c2c_bram_rst_clk_wiz_100M_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_vio_0_0/b2000t_c2c_bram_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_vio_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_vio_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila_0/b2000t_c2c_bram_system_ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_system_ila_0 || ORIG_REF_NAME==b2000t_c2c_bram_system_ila_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_jtag_axi_0_0/b2000t_c2c_bram_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_jtag_axi_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_jtag_axi_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_xbar_0/b2000t_c2c_bram_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_xbar_0 || ORIG_REF_NAME==b2000t_c2c_bram_xbar_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila1_0/b2000t_c2c_bram_system_ila1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_system_ila1_0 || ORIG_REF_NAME==b2000t_c2c_bram_system_ila1_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_xlconstant_0_0/b2000t_c2c_bram_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_xlconstant_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_xlconstant_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_aurora_64b66b_0_1/b2000t_c2c_bram_aurora_64b66b_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_aurora_64b66b_0_1 || ORIG_REF_NAME==b2000t_c2c_bram_aurora_64b66b_0_1}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_chip2chip_0_1/b2000t_c2c_bram_axi_chip2chip_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_axi_chip2chip_0_1 || ORIG_REF_NAME==b2000t_c2c_bram_axi_chip2chip_0_1}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_1_0/b2000t_c2c_bram_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_1_0 || ORIG_REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_1_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_1_bram_1/b2000t_c2c_bram_axi_bram_ctrl_1_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_1_bram_1 || ORIG_REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_1_bram_1}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_dut_0_0/b2000t_c2c_bram_dut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_dut_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_dut_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_axi_bram_ctrl_0_1/b2000t_c2c_bram_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_0_1 || ORIG_REF_NAME==b2000t_c2c_bram_axi_bram_ctrl_0_1}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_jack_0_0/b2000t_c2c_bram_jack_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_jack_0_0 || ORIG_REF_NAME==b2000t_c2c_bram_jack_0_0}]

# IP: bd/b2000t_c2c_bram/ip/b2000t_c2c_bram_system_ila2_0/b2000t_c2c_bram_system_ila2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2000t_c2c_bram_system_ila2_0 || ORIG_REF_NAME==b2000t_c2c_bram_system_ila2_0}]

# XDC: bd/b2000t_c2c_bram/b2000t_c2c_bram_ooc.xdc
