# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0.xci
# IP: The module: 'axi_chip2chip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_chip2chip_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_chip2chip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_chip2chip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0.xci
# IP: The module: 'axi_chip2chip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_chip2chip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_chip2chip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/GITHUB/vivado/zynq_c2c/zynq_c2c.srcs/sources_1/ip/axi_chip2chip_0/axi_chip2chip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_chip2chip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
