# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0.xci
# IP: The module: 'zynq_iic_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_iic_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_iic_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_iic_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0.xci
# IP: The module: 'zynq_iic_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_iic_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_iic_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/wesleyguo/demo_2016.4_wesleyguo/zynq_iic/zynq_iic.srcs/sources_1/bd/zynq_iic/ip/zynq_iic_proc_sys_reset_0_0/zynq_iic_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_iic_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
